### ISSUE TITLE
[TASK] Register hook for all onlineMediaHelpers

### ISSUE THREAD

**Issue by ayacoo** [b13/online-media-updater#4]
In https://github.com/b13/online-media-updater/blob/main/Classes/Hooks/AddOnlineMediaUpdater.php#L47 is firmly checked on youtube and vimeo. Each media extension can be enabled here, as they must adhere to a fixed scheme. I had just tested it with EXT:tiktok

Here you can get some inspiration from the isOnlineMedia() function. We can use the keys from the array $GLOBALS['TYPO3_CONF_VARS']['SYS']['fal']['onlineMediaHelpers']

**Comment by ochorocho** [comment]
Done with https://github.com/b13/online-media-updater/commit/5285af13a9f1cc9e4a03d9afc1c18f0df336f22f
