### ISSUE TITLE
Empty JsonResponse leads to endless loading

### ISSUE THREAD

**Issue by schliesser** [b13/online-media-updater#6]
TYPO3 10.4.31
online-media-updater 1.0.2

The controller action for the Media Update ends with an empty JsonResponse. The TYPO3 10 Backend is waiting endlessly for the ajax route result. (Orange loading bar and spinner)

```php
return new JsonResponse();
```

When I add some value to the response it finishes very fast with a green flash message

```php
return new JsonResponse(['success' => $previewPath]);

or

return new JsonResponse(['success']);
```

**Comment by ochorocho** [comment]
This is fixed now :-)
